name: CI-master

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  # Build code, run tests, and upload Docker images.
  build_test_push:
    runs-on: ubuntu-latest
    env: 
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.repository_owner}} --password-stdin

      - name: Start Docker container
        run: docker-compose up --build -d dev

      - name: Build code
        run: docker-compose exec -T dev /bin/bash -c "source ~/.bashrc && ./build.sh"

      - name: Run tests
        run: docker-compose exec -T dev /bin/bash -c "source ~/.bashrc && cd controls/build && ./aviata_test"

      - name: Stop Docker container
        run: docker-compose down

      - name: Push Docker images
        if: github.event_name == 'push'
        run: |
          docker-compose build prod
          docker-compose push dev
          docker-compose push prod
